[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
sigil_registry = "BWppEKBBET8EJWsi1QaudVWwhaPX7JhNLDDpfHcCjmwe"

[programs.localnet]
sigil_registry = "BWppEKBBET8EJWsi1QaudVWwhaPX7JhNLDDpfHcCjmwe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/node/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
