name = "sigil-protocol-worker"
main = "src/index.ts"
compatibility_date = "2024-02-07"
compatibility_flags = ["nodejs_compat"]

[vars]
SOLANA_RPC_URL = "https://api.devnet.solana.com"
PORT = "3001"
USDC_MINT = "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU"
PROTOCOL_TREASURY = "3adsGFsaGUDePR61ZtvkwkkpCeLne6immQbp2gR5jbfo"
